export enum TypeErrorCode {
  DUPLICATED_ERROR = "DUPLICATED_ERROR",
  NOT_FOUND = "NOT_FOUND",
  ForBIDDEN = "ForBIDDEN",
  UNAUTHORIZE = "UNAUTHORIZE",
  SERVICE_DISABLE = "SERVICE_DISABLE",
  Error_DISABLE = "SERVICE_DISABLE" ,
  BAD_REQUEST = "BAD_REQUEST",


}

