export enum TypeErrorCode {
  DUPLICATED_ERROR = "DUPLICATED_ERROR" ,
  NOT_FOUND = "NOT_FOUND" ,
  ForBIDDEN ="ForBIDDEN" ,
  UNAUTHORIZE = "UNAUTHORIZE" ,
  SERVICE_DISABLE="SERVICE_DISABLE" ,


}

